Content:
    viscosity_sintering:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: viscosity_sintering
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
